# Generated by Django 5.2.10 on 2026-02-02 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='raw/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('camera_make', models.CharField(blank=True, max_length=50, null=True)),
                ('camera_model', models.CharField(blank=True, max_length=50, null=True)),
                ('iso', models.IntegerField(blank=True, null=True)),
                ('shutter_speed', models.CharField(blank=True, max_length=30, null=True)),
                ('aperture', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_type', models.CharField(choices=[('THUMB', 'Thumbnail'), ('PREVIEW', 'Preview'), ('WATERMARK', 'Watermarked')], max_length=20)),
                ('file', models.ImageField(upload_to='variants/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='processor.rawasset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('asset', 'variant_type'), name='unique_variant_per_asset')],
            },
        ),
    ]
